version: '3.8'

services:

  db:
    image: mysql
    restart: always
    container_name: db-beers
    build: ./sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
    ports:
      - "3307:3306"